### PR TITLE
github-bot-jscpdrc 추가

### PR DESCRIPTION
**Pull request by chul-hyun**
### 이런게 변경되었어요. 💍
- copy / pasts 분석 도구 봇 추가

### Reference
- [jscpd](https://github.com/kucherenko/jscpd)
- [jscpd-github-bot](https://github.com/apps/jscpd-github-bot)

### CODE REVIEW

**Comment by chul-hyun** [comment]
Hey @vomvoru,  
Your changes look good to me!

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;snack-news&#x2F;Snack-BE&#x2F;builds&#x2F;588284452">View build log</a>

###### TravisBuddy Request Identifier: c19de6f0-ddb9-11e9-92dc-af5afd331ce9

**Comment by chul-hyun** [comment]
결과가 뭔가 필요 없는 결과들도 있지만.. ㅎㅎ
아래와 같은것도 있고 추후 코드에 의미가 있는 사항이 있을수도 있으니..

Clone found (java):
 - [src/main/java/com/snack/news/domain/tag/Tag.java#L25-L35](https://github.com/snack-news/Snack-BE/blob/github-bot-jscpd/src/main/java/com/snack/news/domain/tag/Tag.java#L25-L35)
   [src/main/java/com/snack/news/domain/category/Category.java#L24-L34](https://github.com/snack-news/Snack-BE/blob/github-bot-jscpd/src/main/java/com/snack/news/domain/category/Category.java#L24-L34)

Clone found (java):
 - [src/main/java/com/snack/news/domain/tag/Tag.java#L38-L47](https://github.com/snack-news/Snack-BE/blob/github-bot-jscpd/src/main/java/com/snack/news/domain/tag/Tag.java#L38-L47)
   [src/main/java/com/snack/news/domain/category/Category.java#L37-L46](https://github.com/snack-news/Snack-BE/blob/github-bot-jscpd/src/main/java/com/snack/news/domain/category/Category.java#L37-L46)

이전 코드의 copy/paste 에 대한 diff를 보여주는 기능은 없지만, 시간될때 bot 코드 수정해서,
추후 넣어보려고 합니다

**Comment by chul-hyun** [comment]
Hey @vomvoru,  
Your changes look good to me!

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;snack-news&#x2F;Snack-BE&#x2F;builds&#x2F;588326179">View build log</a>

###### TravisBuddy Request Identifier: 6e5362e0-ddd2-11e9-a6ae-3d939d1fbff1

**Review by Delf-Lee — APPROVED** [review]

**Review by NESOY — APPROVED** [review]

**Comment by chul-hyun** [comment]
봇이 돌아가는 서버(heroku)쪽의
자원이나 코드의 문제로 처음 몇번만 되고 이후에는 안되는 증상이 있네요 ㅠㅠ

클라이언트쪽 코드는 문제 및 변경이 필요한 부분은 없을 예정이라서 머지후 시간될때 살펴보겠슴다

**Comment by chul-hyun** [comment]
Hey @vomvoru,
Something went wrong with the build.

TravisCI finished with status `errored`, which means the build failed because of something unrelated to the tests, such as a problem with a dependency or the build process itself.

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;snack-news&#x2F;Snack-BE&#x2F;builds&#x2F;592236960">View build log</a>

###### TravisBuddy Request Identifier: c470baa0-e48b-11e9-8762-674d3eb5305e

**Pull request merged**
